### ISSUE TITLE
Add New project 

### ISSUE THREAD

**Issue by sandeep1324** [Jayshah6699/datascience-mashup#10]
I want to add my project which reviews your Twitter tweet with the help of a graph or any other chart type by google sheets in terms of the Number of retweets, Positive tweets, Negative Tweets, and their difference as a Net score.

**Comment by Jayshah6699** [comment]
can you share your project link?

**Comment by Jayshah6699** [comment]
@sandeep1324 let me see that project first so that I can assign the level tag based on that
