### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by kanishkaa24** [Jayshah6699/datascience-mashup#100]
I would Love to create a logo for this project. Kindly add the labels and assign it to me if you're fine with the suggestion. @Jayshah6699

**Comment by kanishkaa24** [comment]
In this issue, I'll be creating logos for each project and adding them to the website. 
This is a level 5 issue.

**Comment by kanishkaa24** [comment]
![ADULT CENSUS INCOME](https://user-images.githubusercontent.com/71253790/104466392-30365d00-55db-11eb-87a2-173604285361.png)
This is a demo logo for the ADULT CENSUS INCOME project. I'm hoping to create all the logos on the same lines with relevant images. Please tell me if you're fine with this. @Jayshah6699

**Comment by Jayshah6699** [comment]
Rather than just going by exact same name you can go with more meaningful name or with name which explains the project more effectively. @kanishkaa24  If possible make different unique logos according to the project.

**Comment by kanishkaa24** [comment]
> Rather than just going by exact same name you can go with more meaningful name or with name which explains the project more effectively. @kanishkaa24  If possible make different unique logos according to the project.

Yes @Jayshah6699 . I'll be making different logos. As for the names, do you have any suggestions?

**Comment by Jayshah6699** [comment]
Yes I do. For example here we have dog vs cat so you can name it Dog/Cat classifier. @kanishkaa24

**Comment by kanishkaa24** [comment]
> Yes I do. For example here we have dog vs cat so you can name it Dog/Cat classifier. @kanishkaa24 

@Jayshah6699 
Please help me with other names as well as it would be really difficult to come up on my own for 15 projects.

**Comment by kanishkaa24** [comment]
@Jayshah6699 
I have made a PR for Dogs/Cats Classifier. 
How do you like the name PINK AND POWERFUL for Breast Cancer Prediction Project?

**Comment by kanishkaa24** [comment]
![2](https://user-images.githubusercontent.com/71253790/104578902-4b5ba800-5681-11eb-8b68-24efac6d3b24.png)
![3](https://user-images.githubusercontent.com/71253790/104578907-4d256b80-5681-11eb-80b1-1853396c0c89.png)
![4](https://user-images.githubusercontent.com/71253790/104578914-4f87c580-5681-11eb-84b6-5d782aeb36e8.png)
![5](https://user-images.githubusercontent.com/71253790/104578935-531b4c80-5681-11eb-8806-6143cde0f9da.png)
![6](https://user-images.githubusercontent.com/71253790/104578947-57476a00-5681-11eb-94b6-e302407a606d.png)
@Jayshah6699 
Kindly review the logos and the names. Let me know if there are any changes.

**Comment by Jayshah6699** [comment]
Those are really good! Great work! @kanishkaa24

**Comment by kanishkaa24** [comment]
> Those are really good! Great work! @kanishkaa24 

Shall I make PRs for the same?
