### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [Jayshah6699/datascience-mashup#106]
Hi @Jayshah6699  
I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time
( config file having a  proper message)

Kindly do assign me this issue

For reference, kindly check out: https://github.com/apps/welcome

**Comment by akrish4** [comment]
Hi @Jayshah6699 

This is for your kind information , This is not a documentation issue , Please kindly add a Level-3 or Level-4 label , This is a feature issue

**Comment by Jayshah6699** [comment]
@akrish4 you can have maximum level 2 tag for good welcome bot integration level 3 is for bug fix and level 4 is for implementing new feature to the project since you are not doing none you can not have that

**Comment by akrish4** [comment]
okay @Jayshah6699  , thank you for the detailed explanation

**Comment by akrish4** [comment]
@Jayshah6699 
kindly assign , i will open pr soon

**Comment by akrish4** [comment]
#148   PR

**Comment by akrish4** [comment]
Install the bot and select the repository you wish the bot is needed  https://github.com/apps/welcome and guess what ??
thatsall done , now bot will do rest everything on its own
