### ISSUE TITLE
A python script which refine a dataset to feed it into a model 

### ISSUE THREAD

**Issue by Rohit-bisht-rise** [Jayshah6699/datascience-mashup#11]
There are issues with the **scikit learn** library that it can't be fed with *NULL* (missing values) and *String (Object)* data-type.
Hence a Data Scientist(beginners or who don't have any trick yet) has to give his extra time to clean the Data (or dataset),
#### I want to build a python script that does the following tasks:
>1. take input data 
> -it can take any format (like  .xslx, .csv )
>2. drop duplicates rows, columns 
>3. Impute missing values.
>4. Change the Object data-type to a model fed datatype( **uint** )
>5. Output the file ( with same name and extension as given)

Whoo! the newly created file is ready to feed into any model

You may check one of my predicting models' file, where I have been gone through to clean the dataset before feeding into it a model.
check the file [here](https://github.com/Rohit-bisht-rise/Bank-Churn-Prediction/blob/master/prediction_models.ipynb).
@Jayshah6699 Please check it and put the tags accordingly and assign to me.

**Comment by Jayshah6699** [comment]
Best of luck! @Rohit-bisht-rise
