### ISSUE TITLE
Generating Word Cloud For a Text File

### ISSUE THREAD

**Issue by gargnityansh** [Jayshah6699/datascience-mashup#113]
Word Cloud are recently the most common way to recognize the highly used words in a very interesting picture format.

**Comment by gargnityansh** [comment]
> Word Cloud are recently the most common way to recognize the highly used words in a very interesting picture format.

@Jayshah6699 please assign this issue to me, so that I start building upon.

**Comment by Jayshah6699** [comment]
It is a great way of visualisation and nice use of NLP. GO for it.

**Comment by Jayshah6699** [comment]
Make sure you add those in Different visualisations folder only by making new folder named word cloud.
