### ISSUE TITLE
Fake news Detection using TfidfVectorizer

### ISSUE THREAD

**Issue by shraiyya** [Jayshah6699/datascience-mashup#115]
The fake news detector can be made using TfidfVectorizer and initializing the Passive Aggressive classiﬁer. It helps in the detection of fake news.
Please add the DWOC label and level of the issue.

**Comment by Jayshah6699** [comment]
Just mention which dataset are you gonna use.

**Comment by shraiyya** [comment]
Yes Sure.
Kaggle Dataset : https://www.kaggle.com/c/fake-news/data
