### ISSUE TITLE
Nautral language processing on reviews

### ISSUE THREAD

**Issue by kenkirito** [Jayshah6699/datascience-mashup#118]

**Comment by Jayshah6699** [comment]
What kind of processing?

**Comment by kenkirito** [comment]
On single review and reviews by loop

**Comment by Jayshah6699** [comment]
You need to elaborate a lot more than this. @kenkirito

**Comment by kenkirito** [comment]
Python NLTK: nalysis

**Comment by Jayshah6699** [comment]
I do not think this will be suitable to my repo
