### ISSUE TITLE
New Data Science Project "Coronary Heart Disease Prediction Web App"

### ISSUE THREAD

**Issue by IndraP24** [Jayshah6699/datascience-mashup#12]
In this project, we will use various models for predicting the **10-year CHD** of a person based on the features provided in the dataset and use a web app for users to select any of the models and view the results obtained from them. Users won't be able to input data for prediction since there are a lot of features but will be able to input hyperparameters of their choice if required. Options will also be provided to choose among various metrics available for viewing.

### Dataset: 
[Framingham](https://www.kaggle.com/amanajmera1/framingham-heart-study-dataset) from Kaggle, a single CSV file.

### Models:
Using both scikit-learn and TensorFlow.

### Web App:
Using either Streamlit or Flask (yet to be decided)

### Web Hosting:
Using either Streamlit-sharing or Heroku

Any suggestions are always welcome.

**Comment by Jayshah6699** [comment]
Tell your team members to comment here all of working ones should get an assignment and if you are in any college and have college domain email address then you can get student developer pack and from that, you can get an actual domain name from either name.com or .tech domains. Otherwise, good idea go one. @IndraP24

**Comment by IndraP24** [comment]
Okay, I'll get a student developer pack and go for an actual domain name. But I don't have a team since it's easy to build a simple web app using the Streamlit module for Data Science models. I'll build one initially but if a better web design is required along with an extensive backend, then it would be really helpful if someone else contributes to this too. 

Thanks for the suggestions.

**Comment by Rohit-bisht-rise** [comment]
@IndraP24 I recently used the Django framework for website development, so if you require contribution ( especially in the backend) tag me

**Comment by IndraP24** [comment]
@Rohit-bisht-rise Sure I would. I'm thinking of initially building one using the Streamlit module of python which binds frontend and backend together. But it's really simple and usually used for very small applications like this one. But in case it escalates to a bigger implementation, then it would require both frontend and backend separately. I'll update once the initial model is complete.
