### ISSUE TITLE
Natural Disaster Prediction

### ISSUE THREAD

**Issue by infiniteoverflow** [Jayshah6699/datascience-mashup#130]
@Jayshah6699 i would like to contribute this model to the repo as a part of DWOC 21'

Dataset used : https://www.kaggle.com/aswin1871/cyclonewildfireflood-and-earthquake

Classes : Cyclone , Wildfire , Floods and Earthquake

Kindly let me know your views on the same.

**Comment by Jayshah6699** [comment]
upload this dataset on kaggle make it public add link here and then start working. @infiniteoverflow

**Comment by infiniteoverflow** [comment]
> upload this dataset on kaggle make it public add link here and then start working. @infiniteoverflow

I have updated with the kaggle link.
