### ISSUE TITLE
Recreating fashion MNIST like images using GAN, Tensorflow 

### ISSUE THREAD

**Issue by madhurima99** [Jayshah6699/datascience-mashup#133]
I would like to apply **Generative adversarial networks (GANs)** to generate images from **noise** like in fashion MNIST.
For the same, I will be using **tf.keras.datasets** module to load the Fashion MNIST dataset.

@Jayshah6699 I'm participating in **DWOC.** It would be great if you assign this issue to me.
Thank you.

**Comment by Jayshah6699** [comment]
All the best!

**Comment by madhurima99** [comment]
Thank you!
