### ISSUE TITLE
Predicting Employee turnover using Scikit Learn

### ISSUE THREAD

**Issue by shraiyya** [Jayshah6699/datascience-mashup#137]
Dataset used: https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Employee+Churn+in+Python/HR_comma_sep.csv

Please assign me this issue and add DWOC tag.

**Comment by Jayshah6699** [comment]
Explain your approach!

**Comment by shraiyya** [comment]
It can predict if an employee can quit or not based on a number of projects, average hours, work accidents, etc. 
Implementation is done by using Python’s Scikit-Learn library.
The supervised learning classifiers used in the project are random forest and decision trees.




number_project | average_montly_hours | time_spend_company | Work_acciden
-- | -- | -- | --
