### ISSUE TITLE
Heart Disease - Classifications (Machine Learning)

### ISSUE THREAD

**Issue by kenkirito** [Jayshah6699/datascience-mashup#139]
We have a data which classified if patients have heart disease or not according to features in it. We will try to use this data to create a model which tries predict if a patient has this disease or not. We will use logistic regression (classification) algorithm.

**Comment by Jayshah6699** [comment]
add link of the dataset and elaborate approach.

**Comment by kenkirito** [comment]
https://www.kaggle.com/aavigan/cleveland-clinic-heart-disease-dataset?select=processed_cleveland.csv

**Comment by kenkirito** [comment]
dataset

**Comment by kenkirito** [comment]
I will be building a machine learning model based on logistic regression and it will Give clinical parameters about a patient, how well can we predict whether or not they have heart disease?

**Comment by Jayshah6699** [comment]
elaborate your question a littlebit

**Comment by kenkirito** [comment]
i am gonna use decison tree, knn and random forest. i am using feature selection seaborn(to get correlation of each data) and data preprocessing

**Comment by kenkirito** [comment]
done can I make a pr?

**Comment by Jayshah6699** [comment]
sure

**Comment by kenkirito** [comment]
@Jayshah6699 please check the pr
