### ISSUE TITLE
Sound classification

### ISSUE THREAD

**Issue by Jayshah6699** [Jayshah6699/datascience-mashup#141]
Classify sounds using the dataset given below.
https://urbansounddataset.weebly.com/urbansound8k.html

You need to classify sounds into these following categories.
0 = air_conditioner
1 = car_horn
2 = children_playing
3 = dog_bark
4 = drilling
5 = engine_idling
6 = gun_shot
7 = jackhammer
8 = siren
9 = street_music

**Comment by AmanSingh0-0** [comment]
I would like to work on this. I am thinking of creating a Convolutional Network Model using Keras running over Tensorflow with a few layers. The dataset is quite big. So, give me about a week to do it.

@Jayshah6699 I'm participating in DWOC. It would be great if you assign this issue to me.
Thank you.
