### ISSUE TITLE
Butterfly Classification

### ISSUE THREAD

**Issue by AmanSingh0-0** [Jayshah6699/datascience-mashup#143]
I would like to work on a butterfly classification problem(as I already have the data for it)

@Jayshah6699 I'm participating in DWOC. It would be great if you assign this issue to me.
Thank you.

**Comment by Jayshah6699** [comment]
add the link of the dataset and elaborate your approach too.

**Comment by AmanSingh0-0** [comment]
dataset link-  [http://www.josiahwang.com/dataset/leedsbutterfly/](url)
Approach- I was thinking of expanding on Resnet or Xception

**Comment by AmanSingh0-0** [comment]
@Jayshah6699  Kindly assign this to me
