### ISSUE TITLE
Realtime face-recognition using KNN

### ISSUE THREAD

**Issue by shatakshisingh24** [Jayshah6699/datascience-mashup#150]
Hi! I would like to add a small project on real-time face recognition using KNN , where I will be writing KNN code without sklearn with proper comments for better understanding of user.

**Comment by shatakshisingh24** [comment]
@Jayshah6699 please assign me this issue if it could be done here. I would like to do as a part of DWOC. Thanks

**Comment by Jayshah6699** [comment]
@shatakshisingh24 It is already done in the face gender and age detector. You can try some different project.
