### ISSUE TITLE
Add project content names and links along with contributors

### ISSUE THREAD

**Issue by Jayshah6699** [Jayshah6699/datascience-mashup#154]
Add project content names and contributors in the main readme file. Some new attractive readme file is also acceptable.

**Comment by Amit366** [comment]
Sir I would like to work on this.

**Comment by Amit366** [comment]
Sir how will I know whose name to add and also the project content??

**Comment by Jayshah6699** [comment]
from the repo it self

**Comment by Amit366** [comment]
Project contents from the repo I can add but the contributors names are already there I guess.

**Comment by Amit366** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/60662775/104918284-867c1500-59ba-11eb-8b90-96a29be69a94.png)

**Comment by Amit366** [comment]
sir getting this error

**Comment by Jayshah6699** [comment]
this issue is solved check discord

**Comment by Amit366** [comment]
Then I need not solve?

**Comment by Amit366** [comment]
Sir, the number of project contents in the readme. Md file don't match the number of projects in the repo.

**Comment by Amit366** [comment]
Sir, is there any error in my PR
