### ISSUE TITLE
Credit card fraud transaction detection using python

### ISSUE THREAD

**Issue by Jayshah6699** [Jayshah6699/datascience-mashup#155]
Select some dataset from kaggle and make a model with python technology stack to predict fraud transaction done using a credit card.

**Comment by AmanSingh0-0** [comment]
I would like to work on this.

**Comment by Jayshah6699** [comment]
Explain your approach and mention the link of the dataset you want to use.

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by kenkirito** [comment]
using Scikit Learn

**Comment by AmanSingh0-0** [comment]
Dataset link-  [https://www.kaggle.com/mlg-ulb/creditcardfraud](url)
and as for approach, I was thinking of a CNN model or RandomForest Classifier or some similar classifier(whichever provides better accuracy)
@Jayshah6699 Kindly assign this to me
