### ISSUE TITLE
Flight Price Prediction 

### ISSUE THREAD

**Issue by bharath-acchu** [Jayshah6699/datascience-mashup#171]
Flight Price prediction is an web application - which predicts the price of the flight based on the number of inputs.
Tech stack - flask,machinelearning,deeplearning
dataset : kaggale

**Comment by Jayshah6699** [comment]
It's kaggle and mention the link of the dataset you are going to use.

**Comment by bharath-acchu** [comment]
@Jayshah6699 Sorry My bad :/
Dataset link : https://www.kaggle.com/nikhilmittal/flight-fare-prediction-mh

**Comment by bharath-acchu** [comment]
@Jayshah6699  and Please open this [issue](https://github.com/Jayshah6699/datascience-mashup/issues/9), I was actually working on it!!, Please assign me both!!!
