### ISSUE TITLE
Bitcoin Price Prediction

### ISSUE THREAD

**Issue by AmanSingh0-0** [Jayshah6699/datascience-mashup#173]
Dataset link - [https://www.kaggle.com/mczielinski/bitcoin-historical-data](https://www.kaggle.com/mczielinski/bitcoin-historical-data)

I was thinking of applying LSTM on this, and maybe plot it

**Comment by AmanSingh0-0** [comment]
@Jayshah6699  I'm participating in DWOC. It would be great if you assign this issue to me.
Thank you.

**Comment by Jayshah6699** [comment]
Which plots are you gonna provide?
