### ISSUE TITLE
predicting stock price with previous values and current news

### ISSUE THREAD

**Issue by Bhagyashri2000** [Jayshah6699/datascience-mashup#180]
I would like to collaborate two models and predict stock price
1] Stock price prediction using LSTM (on previous stock price data)
2] Stock sentiment analysis using news headlines

**Comment by Jayshah6699** [comment]
Mention the link of the dataset you are going to use and also elaborate your approach in a little bit depth. @Bhagyashri2000

**Comment by Jayshah6699** [comment]
How many more days do you gonna take @Bhagyashri2000 to complete this project?

**Comment by Bhagyashri2000** [comment]
I am sorry sir. I am in the middle of the project and my end sem is going on so I couldn't complete it.  Can I submit it till 14th Feb?

**Comment by Amit366** [comment]
Can I work on this issue??

**Comment by Jayshah6699** [comment]
@Amit366 after 14th feb you can work on that till that find some new project to work on
