### ISSUE TITLE
Building own Facial Recognition

### ISSUE THREAD

**Issue by bharath-acchu** [Jayshah6699/datascience-mashup#185]
The task is to build facial recognition where it detects and labels the person. I have created a project where it detects the photo and label the person .
The data is the pics that we need to recognise and label with the name
Tech stack  : Computer vision , deeplearning

**Comment by Jayshah6699** [comment]
How it differs from face age and gender detector(existing project)?

**Comment by bharath-acchu** [comment]
Its a basic face detection, for ex: If we feed image of mine and annotate it with my name , then when I pass my image ( another image ) it will recognize and label with my name!!
