### ISSUE TITLE
Data Science Project "Facial Expression Recognition"

### ISSUE THREAD

**Issue by vaishnavi-1** [Jayshah6699/datascience-mashup#194]
I will train the dataset from kaggle to recognize the facial emotions like anger, sad, happy etc. I will make a Convolutional Neural Network model to train the dataset. @Jayshah6699 Kindly add the labels and assign this issue to me.

**Comment by Jayshah6699** [comment]
How many days are you gonna take more to complete  this project?

**Comment by vaishnavi-1** [comment]
Actually my exams are going on..So, I couldn't complete it on time.. I will do it asap. Sorry for the delay.
