### ISSUE TITLE
Text generator project

### ISSUE THREAD

**Issue by Amit366** [Jayshah6699/datascience-mashup#198]
This project is to train the system to complete an incomplete sentence. 

Sir I am a DWOC participant and please allow me to work on this.

**Comment by Jayshah6699** [comment]
You need to elaborate more.

**Comment by Amit366** [comment]
@Jayshah6699 I mentioned it on discord and you approved it

**Comment by Amit366** [comment]
@Jayshah6699 I have sent the PR. Please review it.

**Comment by Jayshah6699** [comment]
Can you tell me your discord name?

**Comment by Amit366** [comment]
Amit Kumar Mishra

**Comment by Amit366** [comment]
@Jayshah6699 Sir in the merged PR it is showing as level 3 but in the issues it is showing level 4.
