### ISSUE TITLE
readme.md file for breast cancer prediction

### ISSUE THREAD

**Issue by Pranjal-2001** [Jayshah6699/datascience-mashup#20]

**Comment by Pranjal-2001** [comment]
Can I start working on it?

**Comment by Jayshah6699** [comment]
@Pranjal-2001 Yes you can start now.

**Comment by himanshu007-creator** [comment]
https://github.com/Jayshah6699/datascience-mashup/pull/25

**Comment by Pranjal-2001** [comment]
How can I contact you? I have some doubts

**Comment by Jayshah6699** [comment]
@Pranjal-2001 we can chat on discord in data science mashup channel. or pm me over there.
