### ISSUE TITLE
Document Matcher

### ISSUE THREAD

**Issue by bharath-acchu** [Jayshah6699/datascience-mashup#215]
Identify matching documents using template matching
This script identifies matching documents (represented as images) which belong to the same vendor by extracting their logos and computing the normalized mean squared error between them.

Techstack : numpy, opencv , Scikit-image , matplotlib

datasets:  [Ghega dataset](https://machinelearning.inginf.units.it/data-and-tools/ghega-dataset)

**Comment by bharath-acchu** [comment]
Hey my score has not been updated in leaderboard. Can you please look into it ?!!

**Comment by Jayshah6699** [comment]
There is a technical glitch. It will be updated within 24 to 48 hours.

**Comment by Jayshah6699** [comment]
Do the changes as soon as possible.
