### ISSUE TITLE
New Project - Predicting whether an employee will be laid off by the company or not

### ISSUE THREAD

**Issue by manvi0308** [Jayshah6699/datascience-mashup#22]

**Comment by Jayshah6699** [comment]
Kindly provide the description @manvi0308

**Comment by manvi0308** [comment]
> _No description provided._

Here's the description :

We could use a dataset and machine learning algorithms to predict using certain factors like years of experience, Salary, that whether the company will fire that employee or not..

I have already worked on this project

**Comment by manvi0308** [comment]
Assign me this as part of DWOC(Devscript winter of code)

**Comment by Jayshah6699** [comment]
Just mention from where you have taken the dataset and add this project in a separate folder as I mentioned before. Also explain your model a little bit like workflow and all. @manvi0308

**Comment by manvi0308** [comment]
Sure, Will explain that
