### ISSUE TITLE
Kickstart Projects Classification

### ISSUE THREAD

**Issue by AmanSingh0-0** [Jayshah6699/datascience-mashup#223]
Dataset link- [https://www.kaggle.com/kemical/kickstarter-projects](https://www.kaggle.com/kemical/kickstarter-projects)
I will be using GradientBoostingClassifier, BaggingClassifier, LGBMClassifier, AdaBoostClassifier, and so on
@Jayshah6699 Kindly assign this to me

**Comment by Jayshah6699** [comment]
When will you be able to finish this project?

**Comment by AmanSingh0-0** [comment]
Give me a couple of days. I am working on some college stuff
