### ISSUE TITLE
New Project - Predicting whether bank will give loan or not to a customer

### ISSUE THREAD

**Issue by manvi0308** [Jayshah6699/datascience-mashup#23]

**Comment by Jayshah6699** [comment]
Description!

**Comment by manvi0308** [comment]
> _No description provided._

Here's the description :

Banks before giving loan to any applicant usually analyze a certain number of factors like applicant's age, education, salary before giving them loan, my project aims to predict that whether an applicant will be given loan or not.

**Comment by manvi0308** [comment]
Kindly assign this issue to me as part of Devscript winter of code

**Comment by Jayshah6699** [comment]
I am assigning this issue to you but I am gonna need the info like from where did you get the dataset and what does the model exactly do and all. @manvi0308

**Comment by manvi0308** [comment]
Sure

**Comment by Jayshah6699** [comment]
@manvi0308 also star the project

**Comment by Amit366** [comment]
Sir I want to work on this issue.

**Comment by Bhagyashri2000** [comment]
I want to work on this issue

**Comment by Amit366** [comment]
Is this issue open??

**Comment by Jayshah6699** [comment]
no
