### ISSUE TITLE
Face Mask Detection

### ISSUE THREAD

**Issue by bharath-acchu** [Jayshah6699/datascience-mashup#235]
Building a real-time system to detect whether the person on the webcam is wearing a mask or not. Training the face mask detector model using Keras and OpenCV.
[dataset](https://www.kaggle.com/andrewmvd/face-mask-detection)

**Comment by Jayshah6699** [comment]
I think in the DWOC there is a separate project for that only

**Comment by Jayshah6699** [comment]
If you want to do that just help her with this project in her repo. And if you have any other idea with any other project open an issue for sure.
