### ISSUE TITLE
Finger Signs Detection using ResNet

### ISSUE THREAD

**Issue by infiniteoverflow** [Jayshah6699/datascience-mashup#238]
Dataset : https://www.kaggle.com/maneesh99/signs-detection-dataset

We can use the ResNet101 Architecture to train a model to classify the images into the various defined classes of the dataset.

**Comment by Jayshah6699** [comment]
I have something in my mind. If you can try to create a machine learning model and create a simple interface which gives an output. Like any sort of output, it doesn't matter. Whichever you can do.  With that interface, I will give you a level 5.

**Comment by infiniteoverflow** [comment]
You mean like a simple gui application that takes an input and gives the output ??

**Comment by Jayshah6699** [comment]
Yes like a gui which captures your image from webcan and gives output in text or similar emoji or something like that

**Comment by infiniteoverflow** [comment]
yeaah sure , will do it.

And i have a pending PR , can you please review it. Then i can start with this work , otherwise it might create conflictsm
