### ISSUE TITLE
Brain tumor detection using neural nets

### ISSUE THREAD

**Issue by bharath-acchu** [Jayshah6699/datascience-mashup#244]
[Dataset link](https://www.kaggle.com/navoneel/brain-mri-images-for-brain-tumor-detection)

**Comment by Jayshah6699** [comment]
You need to explain your approach here too.

**Comment by bharath-acchu** [comment]
Building a detection model using a convolutional neural network in Tensorflow & Keras.
![nnarchitecture](https://user-images.githubusercontent.com/37451492/107103158-9ca32580-6842-11eb-9189-36a88d3ac248.PNG)

**Comment by Amit366** [comment]
Can I work on this issue??
