### ISSUE TITLE
American Sign langaugae Prediction webapp

### ISSUE THREAD

**Issue by bharath-acchu** [Jayshah6699/datascience-mashup#245]
This is an ASL recognition where it detects american sign language. It has been deployed on heroku as web app

**Comment by Jayshah6699** [comment]
Provide dataset which you are gonna use and example too coz Some similar project has been done already as far as I know.

**Comment by bharath-acchu** [comment]
[DATASET](https://drive.google.com/drive/folders/1V2SA8F2ZzoK-7uUJsVO1pnNK5O4UPS2A?usp=sharing)
Project which was done for my internship - [working link is here](https://asl-prediction-web-app-bha.herokuapp.com/)
Example data : 
Alphabet C:
![C16](https://user-images.githubusercontent.com/37451492/107102842-b98b2900-6841-11eb-870e-bf1a64925db7.jpg)
