### ISSUE TITLE
Cuisine Prediction using Sklearn

### ISSUE THREAD

**Issue by shraiyya** [Jayshah6699/datascience-mashup#249]
- The code can predict the cuisine of a recipe, given its ingredients.
- Decision Tree is used for prediction
- Dataset used : https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DS0103EN/labs/data/recipes.csv"
- Please add DWOC tag and level

**Comment by Jayshah6699** [comment]
make a simple interface too where you upload an image and it gives you a list of cuisines that might have been used and I will give you level 5 for that.

**Comment by shraiyya** [comment]
Actually, Its a csv file containing columns like country and the various names of ingredients. There is no image processing involved.
