### ISSUE TITLE
Chicago Crime Rate

### ISSUE THREAD

**Issue by 07yuvraj** [Jayshah6699/datascience-mashup#250]
The dataset of crime rate of chicago that uses  Facebook Prophet Time Series Prediction to analyse the trend of Crime Rate of Chicago over next few years using the available data.

**Comment by Jayshah6699** [comment]
Why do we need Chicago crime rate when you can get a bigger dataset of Delhi practically? hahahha

**Comment by Jayshah6699** [comment]
btw can you do it for Delhi Mumbai or for any indian state or city?

**Comment by 07yuvraj** [comment]
The data is not available for Delhi Mumbai as it is for Chicago
