### ISSUE TITLE
concrete strength prediction

### ISSUE THREAD

**Issue by nitya123-github** [Jayshah6699/datascience-mashup#27]
can i do this project as predicting concrete strength using nueral networks?

**Comment by Jayshah6699** [comment]
Can you describe the project like the data set you are going to use, your approach towards the solution and all. @nitya123-github

**Comment by nitya123-github** [comment]
Yeah i will use data set from UCI machine learning repository and predict the compressive strength  of concrete by using nueral networks which involves datascaling, featurization, etc

**Comment by Jayshah6699** [comment]
Okay @nitya123-github also star the repo
