### ISSUE TITLE
Reducing Traffic Mortality in USA

### ISSUE THREAD

**Issue by shraiyya** [Jayshah6699/datascience-mashup#284]
- The code aims to reduce _Traffic Mortality in the USA_ in a statistically sound way.
- The data given to us was originally collected by the National Highway Traffic Safety Administration and the National Association of Insurance Commissioners. 
- This particular dataset was compiled and released as a CSV-file by FiveThirtyEight under the CC-BY4.0 license.
- Data Visualisation is done with Seaborn and Linear Regression, PCA, and Kmeans algorithms are used.
- Please add the **DWOC Tag and Level**.

**Comment by Jayshah6699** [comment]
Do it for india with indian dataset if possible

**Comment by shraiyya** [comment]
I tried finding the datasets on Kaggle but most of them don't have the features necessary for training. 
They just have the statistics so it's difficult to use Kmeans on that.
