### ISSUE TITLE
Alexa Reviews analysis using NLTK

### ISSUE THREAD

**Issue by infiniteoverflow** [Jayshah6699/datascience-mashup#294]
Dataset : https://www.kaggle.com/sid321axn/amazon-alexa-reviews

Using this dataset , we can analyze Alexa products reviews. We will be using NLTK for text preprocessing followed by RandomForest Classifier to classify the product review into Good / Not Good.

**Comment by Jayshah6699** [comment]
You need to elaborate more about this.

**Comment by infiniteoverflow** [comment]
@Jayshah6699 I have elaborated my approach for the same. Kindly have a look.
