### ISSUE TITLE
Analyzing and Visualizing Uber data 

### ISSUE THREAD

**Issue by Bhagyashri2000** [Jayshah6699/datascience-mashup#344]
Analyzing Uber data (previous trips) to improve service. 
Dataset used: https://www.kaggle.com/fivethirtyeight/uber-pickups-in-new-york-city

**Comment by Jayshah6699** [comment]
You need to elaborate more

**Comment by Bhagyashri2000** [comment]
There are more than 4.5 million trips data in dataset including date, time and location of trip. The project will visualize data so that some interpretations can be made. With this, we can get insights which can help in future decisions and improvement.
