### ISSUE TITLE
Contribution guidlines/ Read me file/ Documentation

### ISSUE THREAD

**Issue by Jayshah6699** [Jayshah6699/datascience-mashup#36]
In this markdown file, there will be contribution guidelines.

**Comment by CharvyJain** [comment]
@Jayshah6699 Can I work on this issue ?

**Comment by Jayshah6699** [comment]
Sure @CharvyJain

**Comment by CharvyJain** [comment]
@Jayshah6699 I made a pull request. Please let me know If there are any changes to make ?

**Comment by Jayshah6699** [comment]
@CharvyJain check the comment and do one thing I just have added the contributors line in the bottom of readme file just copy-paste that part into the file you have created and for bonus do one thing makes two pull requests just copy-paste whole contribution file into readme file. You will get two pull request merged and in both of them mention this issue only.

**Comment by CharvyJain** [comment]
I added the contributors section in my file.
I didn't get you.  Do you want me to merge the whole readme and Contributing.md file ?
Why two pull-requests ?

**Comment by Jayshah6699** [comment]
@CharvyJain keep contrubuting .md as it is but whole thing in to readme too so then whenever someone visits the repo he/she can have the basic knowledge what to do

**Comment by CharvyJain** [comment]
So, the issue has been solved. Right ?

**Comment by Jayshah6699** [comment]
@CharvyJain yes
