### ISSUE TITLE
Update Readme.md of "House Price Prediction" Project

### ISSUE THREAD

**Issue by vaishnavi-1** [Jayshah6699/datascience-mashup#60]
Anyone interested to solve this issue can tell here.. @Jayshah6699 add the labels.

**Comment by Dhriti-Roy** [comment]
Hey, I would like to work on this. Kindly assign it to me.
Thankyou.

**Comment by Dhriti-Roy** [comment]
@Jayshah6699 How can I contact you for any doubts ??

**Comment by Jayshah6699** [comment]
@Dhriti-Roy you can contact me on discord

**Comment by kanishkaa24** [comment]
@Jayshah6699 
Is this issue open for contributions?

**Comment by Jayshah6699** [comment]
It is assigned to @Dhriti-Roy
