### ISSUE TITLE
Stock Price Prediction

### ISSUE THREAD

**Issue by ksdkamesh99** [Jayshah6699/datascience-mashup#70]
Hi @Jayshah6699 

I want to work on predicting the stock closing price of a company using bidirectional LSTM's.
Please assign me this issue so that I can start working

**Comment by Jayshah6699** [comment]
Mention what data set are you going to use and your approach too @ksdkamesh99

**Comment by ksdkamesh99** [comment]
I am using Google stock dataset retrieved from tiingo
