### ISSUE TITLE
Add Issue Template

### ISSUE THREAD

**Issue by muthuannamalai12** [Jayshah6699/datascience-mashup#72]
Hai,
I would love to add an issue template for your repository. This template would have four issues namely bug, documentation, feature, proposal and question

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by Jayshah6699** [comment]
Instead make a readme file for any existing project explaining project which doesn't contain one. @muthuannamalai12 It will be more helpful to people

**Comment by muthuannamalai12** [comment]
> Instead make a readme file for any existing project explaining project which doesn't contain one. @muthuannamalai12 It will be more helpful to people

Ok. Thank you

**Comment by Jayshah6699** [comment]
change issue name and I will assign you the issue

**Comment by muthuannamalai12** [comment]
> change issue name and I will assign you the issue

I will close this issue and open a new issue for Beautifying README.md
