### ISSUE TITLE
car price prediction 

### ISSUE THREAD

**Issue by oshi36** [Jayshah6699/datascience-mashup#84]
I had made car price prediction project and deployed it using Flask framework.
Please allow me to contribute that here.

**Comment by Jayshah6699** [comment]
@oshi36 You need to elaborate more about that like what kind of datasets you have used, Where did you get those, What is your approach for the car price prediction etc.

**Comment by oshi36** [comment]
I had used dataset of CarDekho company taken from Kaggle which has records for new and used cars and helpful for those who want to know the price of car before selling /buying it. This is a regression problem.
The model is made on the basis of features like year of purchasing , no of owners , kms driven , mode of transmission etc and predict the price of a car.
