### ISSUE TITLE
Data Science Project "The Traffic Sign Prediction"

### ISSUE THREAD

**Issue by bharath-acchu** [Jayshah6699/datascience-mashup#9]
This project is all about predicting the traffic signs. The tech stack used here is python,tensorflow,tkinter,cnn and son on. The dataset is obtained from kaggle. It has test and train dataset on which model is going to be trained . Apart from traing the model a tkinter [ python GUI] is made to upload the picture and predict the symbol. So basically it is a standalone application for classifying or predicting the various traffic signs.

**Comment by Jayshah6699** [comment]
Go for it!

**Comment by Jayshah6699** [comment]
@bharath-acchu You have taken a quite long time for this project 
Let me know here or on the discord if you want to do this project or not so that I can assign this project to someone else.

**Comment by Jayshah6699** [comment]
@bharath-acchu due to your less response and long span of time I am unassigning you and closing this issue as this has been completed.

**Comment by bharath-acchu** [comment]
@Jayshah6699  sorry, I'll be contributing to this issue within couple of days, I was working on the same project, please assign this issue !!!
