### ISSUE TITLE
Rap generator using markov chains

### ISSUE THREAD

**Issue by kenkirito** [Jayshah6699/datascience-mashup#91]

**Comment by Jayshah6699** [comment]
@kenkirito  Elaborate project work flow, Dataset source and aim.

**Comment by kenkirito** [comment]
The Markov Chain built on word frequencies alone does not work too well, as it does not consider grammar or semantics. However, it occasionally will generate vaguely real-sounding lyrics!

**Comment by Jayshah6699** [comment]
do you have any example or link kinda something? @kenkirito

**Comment by kenkirito** [comment]
i have build it from a research paper should I share the output

**Comment by kenkirito** [comment]
https://lakshya-gmail-3.tinytake.com/media/f00d72?filename=1610472398573_TinyTake_12-01-2021-10-56-25.png&sub_type=thumbnail_preview&type=attachment&width=1199&height=760

**Comment by Jayshah6699** [comment]
Share the video too. @kenkirito

**Comment by kenkirito** [comment]
sure

**Comment by kenkirito** [comment]
https://user-images.githubusercontent.com/68530218/104368480-20b70580-5542-11eb-9176-007743074680.mp4

**Comment by kenkirito** [comment]
sorry for the bad quality is some problem with my recorder

**Comment by kenkirito** [comment]
can i make a pr ?

**Comment by Jayshah6699** [comment]
Mention issue number in the pull request.

**Comment by kenkirito** [comment]
ok sure thanks

**Comment by kenkirito** [comment]
Check @Jayshah6699

**Comment by Jayshah6699** [comment]
Check the comments
