### ISSUE TITLE
Apple Stock price Prediction using Linear Regression

### ISSUE THREAD

**Issue by shraiyya** [Jayshah6699/datascience-mashup#92]
The model takes the input of the 'Apple' stock prices and outputs the prediction of the Closing price of the stock. It is implemented on Python using Linear Regression Models.Used the Quandl API  to apply ML to the stock market.
Please label this issue as DWOC.
Also please add the level.

**Comment by Jayshah6699** [comment]
Is it possible to scrape latest data or find latest dataset and then train and test model on that dataset.(2019 - 20) Because big variations were present in that time zones only. So it is a tricky part.

**Comment by shraiyya** [comment]
Yes I will try getting the latest data.

**Comment by shraiyya** [comment]
@Jayshah6699 I have added the new CSV files with 2-year data as well as the code.
Do check it
Pull request #97

**Comment by Jayshah6699** [comment]
Nice work! @shraiyya keep contributing!
