### ISSUE TITLE
Rain fall prediction

### ISSUE THREAD

**Issue by Jayshah6699** [Jayshah6699/datascience-mashup#94]
Rainfall Prediction is one of the difficult and uncertain tasks that have a significant impact on human society. 

Timely and accurate forecasting can proactively help reduce human and financial loss. 

This study will present a set of experiments that involves the use of common machine learning techniques to create models that can predict whether it will rain tomorrow or not based on the weather data for that day.

**Comment by shraiyya** [comment]
I would like to work on this issue. Should I use a Kaggle dataset?

**Comment by Jayshah6699** [comment]
Yes you can use kaggle dataset. But it should be big dataset.
