### ISSUE TITLE
Earth quake prediction

### ISSUE THREAD

**Issue by Jayshah6699** [Jayshah6699/datascience-mashup#95]
It is well known that if a disaster occurs in one region, it is likely to happen again. Some regions have frequent earthquakes, but this is only a comparative amount compared to other regions.

So, predicting the earthquake with date and time, latitude and longitude from previous data is not a trend that follows like other things, it happens naturally.

So basically if we have past data we can predict future disasters.
Make machine learning model do it.

I can provide dataset if needed.

**Comment by kenkirito** [comment]
assign me @Jayshah6699

**Comment by Jayshah6699** [comment]
Kindly complete Weather prediction first. @kenkirito

**Comment by infiniteoverflow** [comment]
I would like to work on this issue.
I am planning to use the following dataset:

https://www.kaggle.com/c/LANL-Earthquake-Prediction

I am planning to use the following Regressors on the dataset :
- XGBoost, 
- CatBoost, and 
- Light Gradient Boost Method

Kindly assign me this issue.
