### ISSUE TITLE
Weather prediction

### ISSUE THREAD

**Issue by Jayshah6699** [Jayshah6699/datascience-mashup#96]
Make a machine learning model to predict weather.

**Comment by kenkirito** [comment]
assign me @Jayshah6699

**Comment by kenkirito** [comment]
I will take the data from kaggle

**Comment by kenkirito** [comment]
hey @Jayshah6699 my issue of Markov chains is closed

**Comment by kenkirito** [comment]
https://lakshya-gmail-3.tinytake.com/media/f04f15?filename=1610617588074_TinyTake_14-01-2021-03-16-17.png&sub_type=thumbnail_preview&type=attachment&width=1199&height=760

**Comment by kenkirito** [comment]
i am done with the model and please merge my Markov chains also

**Comment by kenkirito** [comment]
@Jayshah6699 see my pr and please merge my Markov chains also
